# Generated by Django 2.2.5 on 2019-09-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20190918_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
