# Generated by Django 2.2.5 on 2019-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20190918_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
