# Generated by Django 2.2.5 on 2019-09-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_donation_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(choices=[(0, False), (1, True)]),
        ),
    ]
