# Generated by Django 2.2.5 on 2019-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_auto_20190926_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
